import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Image, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Stack, router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "./Icons";
import api from "../../lib/connection";

export default function PersonDirectoryPage({ type }) {
  const insets = useSafeAreaInsets(); const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [more, setMore] = useState(true); const [loading, setLoading] = useState(false);
  const load = useCallback(async (next = 1, reset = false) => { if (loading) return; setLoading(true); try { const safe = query.trim().replaceAll('"', ''); const filter = `person_type="${type}"${safe ? ` && search="${safe}"` : ""}`; const result = await api.collection("persons").getList(next, 12, { filter }); setItems((old) => reset ? result.items : [...old, ...result.items.filter((item) => !old.some((existing) => existing.id === item.id))]); setPage(next); setMore(next < result.totalPages); } finally { setLoading(false); } }, [query, type, loading]);
  useEffect(() => { load(1, true); }, [type]);
  const missing = type === "MISSING";
  return <View style={styles.root}><Stack.Screen options={{ headerShown: false }} />
    <View style={[styles.header, { paddingTop: insets.top + 10 }]}><TouchableOpacity onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={21} color="white" /></TouchableOpacity><Text style={styles.eyebrow}>{missing ? "MISSING PERSONS DIRECTORY" : "WANTED PERSONS DIRECTORY"}</Text><Text style={styles.title}>{missing ? "Missing persons" : "Wanted persons"}</Text><Text style={styles.subtitle}>{missing ? "Search verified missing-person profiles and report useful information." : "Search official wanted-person profiles and submit information securely."}</Text><View style={styles.search}><Ionicons name="search-outline" size={19} color="#64748B" /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={() => load(1, true)} placeholder="Search name, alias or location" placeholderTextColor="#94A3B8" style={styles.input} returnKeyType="search" /></View></View>
    <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, { paddingBottom: insets.bottom + 28 }]} refreshControl={<RefreshControl refreshing={loading && !items.length} onRefresh={() => load(1, true)} />} onEndReached={() => more && !loading && load(page + 1)} onEndReachedThreshold={0.35} ListEmptyComponent={!loading ? <View style={styles.empty}><Ionicons name="search-outline" size={34} color="#94A3B8" /><Text style={styles.emptyTitle}>No matching profiles</Text></View> : null} ListFooterComponent={loading && items.length ? <ActivityIndicator style={{ margin: 20 }} color="#1E3A8A" /> : null} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => router.push(`/persons/${item.id}`)} activeOpacity={0.82}>{item.featured_image_url ? <Image source={{ uri: item.featured_image_url }} style={styles.photo} /> : <View style={[styles.photo, styles.photoEmpty]}><Ionicons name="person-outline" size={34} color="#94A3B8" /></View>}<View style={styles.copy}><Text style={[styles.type, !missing && styles.wanted]}>{type}</Text><Text style={styles.name}>{item.full_name}</Text><Text style={styles.summary} numberOfLines={2}>{item.summary || item.last_seen_location || "Open verified profile"}</Text></View><Ionicons name="chevron-forward" size={18} color="#94A3B8" /></TouchableOpacity>} />
  </View>;
}
const styles = StyleSheet.create({root:{flex:1,backgroundColor:"#F5F7FA"},header:{backgroundColor:"#1E3A8A",paddingHorizontal:18,paddingBottom:22,borderBottomLeftRadius:22,borderBottomRightRadius:22},back:{width:38,height:38,alignItems:"center",justifyContent:"center",marginLeft:-8},eyebrow:{color:"#BFDBFE",fontSize:10,fontFamily:"GoogleSans_600SemiBold",letterSpacing:1.1,marginTop:8},title:{color:"white",fontSize:27,fontFamily:"GoogleSans_700Bold",marginTop:7},subtitle:{color:"#DBEAFE",fontSize:13,lineHeight:18,marginTop:5},search:{height:48,borderRadius:13,backgroundColor:"white",flexDirection:"row",alignItems:"center",paddingHorizontal:13,gap:9,marginTop:18},input:{flex:1,fontSize:14,color:"#111827"},list:{padding:14,gap:10},card:{backgroundColor:"white",borderRadius:14,borderWidth:1,borderColor:"#E5E7EB",padding:10,flexDirection:"row",alignItems:"center",gap:12},photo:{width:82,height:96,borderRadius:11},photoEmpty:{backgroundColor:"#EEF2F7",alignItems:"center",justifyContent:"center"},copy:{flex:1},type:{fontSize:10,fontFamily:"GoogleSans_700Bold",color:"#A16207",letterSpacing:.7},wanted:{color:"#B42318"},name:{fontSize:17,fontFamily:"GoogleSans_700Bold",color:"#111827",marginTop:4},summary:{fontSize:12,color:"#64748B",lineHeight:17,marginTop:4},empty:{alignItems:"center",paddingTop:70},emptyTitle:{fontSize:15,color:"#475569",marginTop:12,fontFamily:"GoogleSans_600SemiBold"}});
