import React, { useEffect, useState } from "react";
import { ActivityIndicator, Image, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Stack, router, useLocalSearchParams } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "../components/Icons";
import api from "../../lib/connection";

const plainText = (html = "") => html.replace(/<br\s*\/?>/gi, "\n").replace(/<\/p>/gi, "\n\n").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").trim();
export default function PersonDetail() {
  const { id } = useLocalSearchParams(); const insets = useSafeAreaInsets(); const [person, setPerson] = useState(null);
  useEffect(() => { api.collection("persons").getOne(id).then(setPerson).catch(() => setPerson(false)); }, [id]);
  if (person === null) return <View style={styles.center}><Stack.Screen options={{ headerShown:false }} /><ActivityIndicator color="#1E3A8A" /></View>;
  if (!person) return <View style={styles.center}><Text>Profile unavailable.</Text><TouchableOpacity onPress={() => router.back()}><Text style={styles.link}>Go back</Text></TouchableOpacity></View>;
  const report = () => router.push({ pathname:"/report/complaint", params:{ case:`person-${person.id}`, person_id:person.id, person_name:person.full_name } });
  return <View style={styles.root}><Stack.Screen options={{ headerShown:false }} /><ScrollView contentContainerStyle={{ paddingBottom: insets.bottom + 100 }}><View style={[styles.hero,{paddingTop:insets.top+8}]}>{person.featured_image_url ? <Image source={{uri:person.featured_image_url}} style={styles.heroImage} resizeMode="cover" /> : null}<View style={styles.gradient} /><TouchableOpacity style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={21} color="white" /></TouchableOpacity><View style={styles.heroCopy}><Text style={styles.type}>{person.person_type} · {person.status}</Text><Text style={styles.name}>{person.full_name}</Text>{person.aliases ? <Text style={styles.alias}>Also known as {person.aliases}</Text> : null}</View></View><View style={styles.body}>{person.summary ? <Text style={styles.lead}>{person.summary}</Text> : null}{person.last_seen_location ? <View style={styles.info}><Ionicons name="location-outline" size={20} color="#1E3A8A" /><View><Text style={styles.infoLabel}>Last seen / known location</Text><Text style={styles.infoValue}>{person.last_seen_location}</Text></View></View> : null}<Text style={styles.description}>{plainText(person.description)}</Text>{person.images?.length ? <><Text style={styles.sectionTitle}>Images</Text>{person.images.map((url,i) => <Image key={`${url}-${i}`} source={{uri:url}} style={styles.attachment} resizeMode="contain" />)}</> : null}{person.documents?.length ? <><Text style={styles.sectionTitle}>Documents</Text>{person.documents.map((document,i) => { const url=typeof document === "string" ? document : document.url; return <TouchableOpacity key={`${url}-${i}`} style={styles.document} onPress={() => Linking.openURL(url)}><Ionicons name="document-text-outline" size={22} color="#1E3A8A" /><Text style={styles.documentText} numberOfLines={1}>View or download document {i+1}</Text><Ionicons name="open-outline" size={17} color="#64748B" /></TouchableOpacity>; })}</> : null}</View></ScrollView><View style={[styles.action,{paddingBottom:Math.max(insets.bottom,12)}]}><TouchableOpacity style={styles.report} onPress={report}><Ionicons name="mic-outline" size={20} color="white" /><Text style={styles.reportText}>I have information</Text></TouchableOpacity></View></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:"#F5F7FA"},center:{flex:1,alignItems:"center",justifyContent:"center"},link:{color:"#1E3A8A",marginTop:12},hero:{height:370,backgroundColor:"#1E3A8A",position:"relative",justifyContent:"flex-end"},heroImage:{...StyleSheet.absoluteFillObject,width:"100%",height:"100%"},gradient:{...StyleSheet.absoluteFillObject,backgroundColor:"#071a4890"},back:{position:"absolute",top:50,left:15,width:42,height:42,borderRadius:21,backgroundColor:"#081a4975",alignItems:"center",justifyContent:"center"},heroCopy:{padding:22},type:{color:"#BFDBFE",fontSize:11,fontFamily:"GoogleSans_700Bold",letterSpacing:.8},name:{color:"white",fontFamily:"GoogleSans_700Bold",fontSize:31,marginTop:6},alias:{color:"#E2E8F0",fontSize:13,marginTop:5},body:{backgroundColor:"white",margin:14,marginTop:-1,borderRadius:16,padding:19,borderWidth:1,borderColor:"#E5E7EB"},lead:{fontSize:17,lineHeight:24,fontFamily:"GoogleSans_600SemiBold",color:"#1F2937",marginBottom:18},info:{flexDirection:"row",gap:11,backgroundColor:"#EFF6FF",borderRadius:12,padding:14,marginBottom:18},infoLabel:{fontSize:11,color:"#64748B"},infoValue:{fontSize:14,color:"#111827",fontFamily:"GoogleSans_600SemiBold",marginTop:2},description:{fontSize:15,lineHeight:24,color:"#334155"},sectionTitle:{fontSize:19,fontFamily:"GoogleSans_700Bold",color:"#111827",marginTop:25,marginBottom:10},attachment:{width:"100%",height:360,backgroundColor:"#F1F5F9",borderRadius:10,marginBottom:10},document:{height:58,borderWidth:1,borderColor:"#E2E8F0",borderRadius:10,paddingHorizontal:13,flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},documentText:{flex:1,fontSize:13,color:"#1F2937"},action:{position:"absolute",bottom:0,left:0,right:0,padding:12,backgroundColor:"white",borderTopWidth:1,borderTopColor:"#E5E7EB"},report:{height:50,borderRadius:12,backgroundColor:"#1E3A8A",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},reportText:{color:"white",fontSize:15,fontFamily:"GoogleSans_700Bold"}});
