import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Image, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Stack, router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "../components/Icons";
import api from "../../lib/connection";

export default function PersonsDirectory() {
  const insets = useSafeAreaInsets(); const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [type, setType] = useState("ALL"); const [page, setPage] = useState(1); const [more, setMore] = useState(true); const [loading, setLoading] = useState(false);
  const load = useCallback(async (next = 1, reset = false) => { if (loading) return; setLoading(true); try { const filters = []; if (query.trim()) filters.push(`search="${query.trim().replaceAll('"', '')}"`); if (type !== "ALL") filters.push(`person_type="${type}"`); const r = await api.collection("persons").getList(next, 12, { filter: filters.join(" && ") }); setItems((old) => reset ? r.items : [...old, ...r.items.filter((x) => !old.some((o) => o.id === x.id))]); setPage(next); setMore(next < r.totalPages); } catch (e) { console.warn("Unable to load persons", e); } finally { setLoading(false); } }, [query, type, loading]);
  useEffect(() => { setItems([]); setMore(true); load(1, true); }, [type]);
  const search = () => load(1, true);
  return <View style={styles.root}><Stack.Screen options={{ headerShown: false }} /><View style={[styles.header, { paddingTop: insets.top + 12 }]}><TouchableOpacity onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={21} color="white" /></TouchableOpacity><Text style={styles.eyebrow}>PUBLIC DIRECTORY</Text><Text style={styles.title}>Missing & wanted persons</Text><Text style={styles.subtitle}>Search verified profiles and share information securely.</Text><View style={styles.search}><Ionicons name="search-outline" size={19} color="#64748B" /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Search name, alias or location" placeholderTextColor="#94A3B8" style={styles.input} returnKeyType="search" />{query ? <TouchableOpacity onPress={() => { setQuery(""); setTimeout(search, 0); }}><Ionicons name="close-circle" size={19} color="#94A3B8" /></TouchableOpacity> : null}</View><View style={styles.filters}>{["ALL", "MISSING", "WANTED"].map((v) => <TouchableOpacity key={v} style={[styles.filter, type === v && styles.filterActive]} onPress={() => setType(v)}><Text style={[styles.filterText, type === v && styles.filterTextActive]}>{v === "ALL" ? "All" : v[0] + v.slice(1).toLowerCase()}</Text></TouchableOpacity>)}</View></View><FlatList data={items} keyExtractor={(x) => x.id} contentContainerStyle={[styles.list, { paddingBottom: insets.bottom + 28 }]} refreshControl={<RefreshControl refreshing={loading && !items.length} onRefresh={() => load(1, true)} />} onEndReached={() => more && !loading && load(page + 1)} onEndReachedThreshold={0.35} ListEmptyComponent={!loading ? <View style={styles.empty}><Ionicons name="search-outline" size={34} color="#94A3B8" /><Text style={styles.emptyTitle}>No matching profiles</Text></View> : null} ListFooterComponent={loading && items.length ? <ActivityIndicator style={{ margin: 20 }} color="#1E3A8A" /> : null} renderItem={({ item }) => <TouchableOpacity style={styles.card} activeOpacity={0.8} onPress={() => router.push(`/persons/${item.id}`)}>{item.featured_image_url ? <Image source={{ uri: item.featured_image_url }} style={styles.photo} /> : <View style={[styles.photo, styles.photoEmpty]}><Ionicons name="person-outline" size={35} color="#94A3B8" /></View>}<View style={styles.copy}><Text style={[styles.type, item.person_type === "WANTED" && styles.wanted]}>{item.person_type}</Text><Text style={styles.name}>{item.full_name}</Text><Text style={styles.summary} numberOfLines={2}>{item.summary || item.last_seen_location || "Open verified profile"}</Text></View><Ionicons name="chevron-forward" size={18} color="#94A3B8" /></TouchableOpacity>} /></View>;
}
const styles = StyleSheet.create({ root:{flex:1,backgroundColor:"#F5F7FA"},header:{backgroundColor:"#1E3A8A",paddingHorizontal:18,paddingBottom:20,borderBottomLeftRadius:22,borderBottomRightRadius:22},back:{width:36,height:36,alignItems:"center",justifyContent:"center",marginLeft:-8},eyebrow:{color:"#BFDBFE",fontSize:10,fontFamily:"GoogleSans_600SemiBold",letterSpacing:1.1,marginTop:8},title:{color:"white",fontSize:25,fontFamily:"GoogleSans_700Bold",marginTop:7},subtitle:{color:"#DBEAFE",fontSize:13,marginTop:5},search:{height:48,borderRadius:13,backgroundColor:"white",flexDirection:"row",alignItems:"center",paddingHorizontal:13,gap:9,marginTop:18},input:{flex:1,fontSize:14,color:"#111827"},filters:{flexDirection:"row",gap:8,marginTop:13},filter:{paddingHorizontal:15,paddingVertical:8,borderRadius:20,backgroundColor:"#ffffff20"},filterActive:{backgroundColor:"white"},filterText:{color:"white",fontSize:12,fontFamily:"GoogleSans_600SemiBold"},filterTextActive:{color:"#1E3A8A"},list:{padding:14,gap:10},card:{backgroundColor:"white",borderRadius:13,borderWidth:1,borderColor:"#E5E7EB",padding:10,flexDirection:"row",alignItems:"center",gap:12},photo:{width:78,height:88,borderRadius:10,objectFit:"cover"},photoEmpty:{backgroundColor:"#EEF2F7",alignItems:"center",justifyContent:"center"},copy:{flex:1},type:{fontSize:10,fontFamily:"GoogleSans_700Bold",color:"#A16207"},wanted:{color:"#B42318"},name:{fontSize:16,fontFamily:"GoogleSans_700Bold",color:"#111827",marginTop:4},summary:{fontSize:12,color:"#64748B",lineHeight:17,marginTop:3},empty:{alignItems:"center",paddingTop:70},emptyTitle:{fontSize:15,color:"#475569",marginTop:12,fontFamily:"GoogleSans_600SemiBold"} });
